// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  wikiSidebar: [
    {
      type: 'category',
      label: 'Voyage of the Stars',
      items: [
        {
          type: 'category',
          label: 'Sessions',
          items: [{ type: 'autogenerated', dirName: 'voyage-of-the-stars/sessions' }],
        },
        {
          type: 'category',
          label: 'Party',
          items: [{ type: 'autogenerated', dirName: 'voyage-of-the-stars/party' }],
        },
      ],
    },
    {
      type: 'category',
      label: 'Keys of Wonder',
      items: [
        {
          type: 'category',
          label: 'Sessions',
          items: [{ type: 'autogenerated', dirName: 'keys-of-wonder/sessions' }],
        },
        {
          type: 'category',
          label: 'Party',
          items: [{ type: 'autogenerated', dirName: 'keys-of-wonder/party' }],
        },
      ],
    },
    {
      type: 'category',
      label: 'World',
      items: [{ type: 'autogenerated', dirName: 'world' }],
    },
  ],
};

module.exports = sidebars;
