// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  wikiSidebar: [
    {
      type: 'category',
      label: 'Voyage of the Stars — Sessions',
      items: [{ type: 'autogenerated', dirName: 'voyage-of-the-stars/sessions' }],
    },
    {
      type: 'category',
      label: 'Keys of Wonder — Sessions',
      items: [{ type: 'autogenerated', dirName: 'keys-of-wonder/sessions' }],
    },
    {
      type: 'category',
      label: 'World',
      items: [
        { type: 'autogenerated', dirName: 'world/northern-wetlands' },
        { type: 'autogenerated', dirName: 'world/grayhaven-area' },
        { type: 'autogenerated', dirName: 'world/general' },
      ],
    },
    {
      type: 'category',
      label: 'Voyage of the Stars',
      items: [
        { type: 'autogenerated', dirName: 'voyage-of-the-stars/party' },
        { type: 'autogenerated', dirName: 'voyage-of-the-stars/plot-threads' },
      ],
    },
    {
      type: 'category',
      label: 'Keys of Wonder',
      items: [
        { type: 'autogenerated', dirName: 'keys-of-wonder/party' },
        { type: 'autogenerated', dirName: 'keys-of-wonder/plot-threads' },
      ],
    },
  ],
};

module.exports = sidebars;
