// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  wikiSidebar: [
    {
      type: 'category',
      label: 'World',
      items: [
        { type: 'autogenerated', dirName: 'world/locations' },
        { type: 'autogenerated', dirName: 'world/npcs' },
        { type: 'autogenerated', dirName: 'world/factions' },
        { type: 'autogenerated', dirName: 'world/deities' },
        { type: 'autogenerated', dirName: 'world/lore' },
        { type: 'autogenerated', dirName: 'world/items' },
      ],
    },
    {
      type: 'category',
      label: 'Voyage of the Stars',
      items: [
        { type: 'autogenerated', dirName: 'voyage-of-the-stars/sessions' },
        { type: 'autogenerated', dirName: 'voyage-of-the-stars/party' },
        { type: 'autogenerated', dirName: 'voyage-of-the-stars/plot-threads' },
      ],
    },
    {
      type: 'category',
      label: 'Keys of Wonder',
      items: [
        { type: 'autogenerated', dirName: 'keys-of-wonder/sessions' },
        { type: 'autogenerated', dirName: 'keys-of-wonder/party' },
        { type: 'autogenerated', dirName: 'keys-of-wonder/plot-threads' },
      ],
    },
  ],
};

module.exports = sidebars;
